# Generated by Django 4.1 on 2022-08-30 14:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Charity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charity_number",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Charity Number",
                    ),
                ),
                (
                    "charity_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Charity Name"
                    ),
                ),
                ("registered_date", models.DateField(verbose_name="Registered Date")),
                (
                    "ceased_date",
                    models.DateField(blank=True, null=True, verbose_name="Ceased Date"),
                ),
                (
                    "reason_for_removal",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Reason for Removal",
                    ),
                ),
                (
                    "known_as",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Known As"
                    ),
                ),
                (
                    "charity_status",
                    models.CharField(max_length=255, verbose_name="Charity Status"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Postcode"
                    ),
                ),
                (
                    "constitutional_form",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Constitutional Form",
                    ),
                ),
                (
                    "previous_constitutional_form_1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Previous Constitutional Form 1",
                    ),
                ),
                (
                    "geographical_spread",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Geographical Spread",
                    ),
                ),
                (
                    "main_operating_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Main Operating Location",
                    ),
                ),
                (
                    "purposes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Purposes",
                    ),
                ),
                (
                    "beneficiaries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Beneficiaries",
                    ),
                ),
                (
                    "activities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="Activities",
                    ),
                ),
                (
                    "objectives",
                    models.TextField(blank=True, null=True, verbose_name="Objectives"),
                ),
                (
                    "principal_office_trustees_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Principal Office/Trustees Address",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "most_recent_year_income",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Most recent year income",
                    ),
                ),
                (
                    "most_recent_year_expenditure",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Most recent year expenditure",
                    ),
                ),
                (
                    "mailing_cycle",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Mailing cycle"
                    ),
                ),
                (
                    "year_end",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="Year End"
                    ),
                ),
                (
                    "date_annual_return_received",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date annual return received",
                    ),
                ),
                (
                    "next_year_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next year end date"
                    ),
                ),
                (
                    "donations_and_legacies_income",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Donations and legacies income",
                    ),
                ),
                (
                    "charitable_activities_income",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Charitable activities income",
                    ),
                ),
                (
                    "other_trading_activities_income",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Other trading activities income",
                    ),
                ),
                (
                    "investments_income",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Investments income"
                    ),
                ),
                (
                    "other_income",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Other income"
                    ),
                ),
                (
                    "raising_funds_spending",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Raising funds spending"
                    ),
                ),
                (
                    "charitable_activities_spending",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Charitable activities spending",
                    ),
                ),
                (
                    "other_spending",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Other spending"
                    ),
                ),
                (
                    "parent_charity_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Parent charity name",
                    ),
                ),
                (
                    "parent_charity_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Parent charity number",
                    ),
                ),
                (
                    "parent_charity_country_of_registration",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Parent charity country of registration",
                    ),
                ),
                (
                    "designated_religious_body",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Designated religious body"
                    ),
                ),
                (
                    "regulatory_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Regulatory Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charity",
                "verbose_name_plural": "Charities",
            },
        ),
        migrations.CreateModel(
            name="CharityFinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charity_number",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Charity Number"
                    ),
                ),
                (
                    "most_recent_year_income",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Most recent year income",
                    ),
                ),
                (
                    "most_recent_year_expenditure",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Most recent year expenditure",
                    ),
                ),
                (
                    "mailing_cycle",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Mailing cycle"
                    ),
                ),
                (
                    "year_end",
                    models.DateField(
                        blank=True, db_index=True, null=True, verbose_name="Year End"
                    ),
                ),
                (
                    "date_annual_return_received",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date annual return received",
                    ),
                ),
                (
                    "next_year_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next year end date"
                    ),
                ),
                (
                    "donations_and_legacies_income",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Donations and legacies income",
                    ),
                ),
                (
                    "charitable_activities_income",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Charitable activities income",
                    ),
                ),
                (
                    "other_trading_activities_income",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Other trading activities income",
                    ),
                ),
                (
                    "investments_income",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Investments income"
                    ),
                ),
                (
                    "other_income",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Other income"
                    ),
                ),
                (
                    "raising_funds_spending",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Raising funds spending"
                    ),
                ),
                (
                    "charitable_activities_spending",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Charitable activities spending",
                    ),
                ),
                (
                    "other_spending",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Other spending"
                    ),
                ),
            ],
            options={
                "verbose_name": "Charity Financial Year",
                "verbose_name_plural": "Charity Financial Years",
                "unique_together": {("charity_number", "year_end")},
            },
        ),
    ]
