# Generated by Django 4.1 on 2022-08-30 11:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Charity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reg_charity_number",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="Reg charity number"
                    ),
                ),
                (
                    "sub_charity_number",
                    models.IntegerField(default=0, verbose_name="Sub charity number"),
                ),
                (
                    "charity_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Charity name"
                    ),
                ),
                ("date_registered", models.DateField(verbose_name="Date registered")),
                ("status", models.CharField(max_length=255, verbose_name="Status")),
                (
                    "date_for_financial_year_ending",
                    models.DateField(verbose_name="Date for financial year ending"),
                ),
                ("total_income", models.BigIntegerField(verbose_name="Total income")),
                (
                    "total_spending",
                    models.BigIntegerField(verbose_name="Total spending"),
                ),
                (
                    "charitable_spending",
                    models.BigIntegerField(verbose_name="Charitable spending"),
                ),
                (
                    "income_generation_and_governance",
                    models.BigIntegerField(
                        verbose_name="Income generation and governance"
                    ),
                ),
                (
                    "retained_for_future_use",
                    models.BigIntegerField(verbose_name="Retained for future use"),
                ),
                (
                    "public_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Public address"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telephone"
                    ),
                ),
                (
                    "company_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Company number",
                    ),
                ),
                (
                    "what_the_charity_does",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        size=None,
                        verbose_name="What the charity does",
                    ),
                ),
                (
                    "who_the_charity_helps",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        size=None,
                        verbose_name="Who the charity helps",
                    ),
                ),
                (
                    "how_the_charity_works",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        size=None,
                        verbose_name="How the charity works",
                    ),
                ),
            ],
        ),
    ]
