# Generated by Django 4.1 on 2022-08-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccni", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charity",
            name="company_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Company number"
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="telephone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Telephone"
            ),
        ),
    ]
