# Generated by Django 4.1 on 2022-08-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ccni", "0002_alter_charity_company_number_alter_charity_telephone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="charity",
            options={"verbose_name": "Charity", "verbose_name_plural": "Charities"},
        ),
    ]
