# Generated by Django 4.1 on 2022-08-23 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="charity",
            options={"verbose_name": "charity", "verbose_name_plural": "charities"},
        ),
        migrations.AlterUniqueTogether(
            name="charityfinancialyear",
            unique_together={("charity", "financial_year_end")},
        ),
    ]
