# Generated by Django 4.1 on 2022-08-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_charity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="tags",
            field=models.ManyToManyField(blank=True, to="documents.tag"),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="charity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_years",
                to="documents.charity",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="data/documents"),
        ),
        migrations.AlterField(
            model_name="document",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="documents.charityfinancialyear",
            ),
        ),
    ]
