# Generated by Django 4.1 on 2022-08-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_document_tags_alter_charityfinancialyear_charity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_type",
            field=models.CharField(
                choices=[("application/pdf", "PDF")],
                default="application/pdf",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="language",
            field=models.CharField(
                choices=[("en", "English")], default="en", max_length=2
            ),
        ),
    ]
