# Generated by Django 4.1 on 2022-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_document_content_type_document_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="charityfinancialyear",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Task ID if the document is currently being fetched",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="charities", to="documents.tag"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="documents", to="documents.tag"
            ),
        ),
    ]
