# Generated by Django 4.1 on 2022-08-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_charityfinancialyear_task_id_alter_charity_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="document_due",
            field=models.DateField(blank=True, null=True),
        ),
    ]
