# Generated by Django 4.1 on 2022-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_alter_charityfinancialyear_document_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charity",
            name="source",
            field=models.CharField(
                choices=[
                    ("CCEW", "Charity Commission for England and Wales"),
                    ("OSCR", "Office of the Scottish Charity Regulator"),
                    ("CCNI", "Charity Commission for Northern Ireland"),
                    ("MAN", "Manually added charity"),
                ],
                default="MAN",
                max_length=4,
            ),
        ),
    ]
