# Generated by Django 4.1 on 2022-08-30 15:49

from multiprocessing.sharedctypes import Value

import autoslug.fields
from django.db import migrations


def migrate_data_forward(apps, schema_editor):
    Tag = apps.get_model("documents", "Tag")
    for instance in Tag.objects.all():
        print(f"Generating slug for {instance}")
        instance.save()  # Will trigger slug update


def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_charity_created_at_charity_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                null=True, editable=False, populate_from="name", unique=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_data_forward, migrate_data_backward),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True
            ),
        ),
    ]
