# Generated by Django 4.1 on 2022-09-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_charityfinancialyear_task_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_text",
            field=models.FileField(blank=True, null=True, upload_to="accounts/txt"),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="accounts/pdf"),
        ),
    ]
