# Generated by Django 4.1 on 2023-02-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_document_file_text_alter_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charity",
            name="date_registered",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="charity",
            name="date_removed",
            field=models.DateField(blank=True, null=True),
        ),
    ]
