# Generated by Django 4.1 on 2024-07-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0016_document_process_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charity",
            name="source",
            field=models.CharField(
                choices=[
                    ("CCEW", "Charity Commission for England and Wales"),
                    ("OSCR", "Office of the Scottish Charity Regulator"),
                    ("CCNI", "Charity Commission for Northern Ireland"),
                    ("MAN", "Manually added charity"),
                ],
                db_index=True,
                default="MAN",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="income",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUCCESS", "Document successfully fetched"),
                    ("FAILED", "Document fetching failed"),
                    ("PENDING", "Document not yet fetched"),
                ],
                db_index=True,
                default=None,
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charityfinancialyear",
            name="status_notes",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="charityfinancialyear",
            index=models.Index(models.F("financial_year_end__year"), name="year_idx"),
        ),
    ]
