# Generated by Django 3.2.9 on 2022-01-10 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccew", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charityannualreturnhistory",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annual_return_history",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityareaofoperation",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area_of_operation",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityarparta",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annual_return_part_a",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityarpartb",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annual_return_part_b",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityclassification",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classification",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityeventhistory",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_history",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charitygoverningdocument",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="governing_document",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityothernames",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_names",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charityotherregulators",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_regulators",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charitypolicy",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charitypublishedreport",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="published_reports",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
        migrations.AlterField(
            model_name="charitytrustee",
            name="charity",
            field=models.ForeignKey(
                db_column="organisation_number",
                help_text="The organisation number for the charity. This is the index value for the charity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trustees",
                to="ccew.charity",
                to_field="organisation_number",
            ),
        ),
    ]
