# Generated by Django 3.2.9 on 2022-02-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccew", "0002_auto_20220110_1235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charity",
            name="charity_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The Main Name of the Charity",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="charity_registration_status",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The charity registration status indicates whether a charity is registered or removed",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charity",
            name="latest_income",
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text="The latest income submitted by the charity. This is the total gross income submitted on part A of the annual return submission.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="charityothernames",
            name="charity_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The Main Name of the Charity",
                max_length=255,
                null=True,
            ),
        ),
    ]
