# Generated by Django 4.0.3 on 2022-05-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccew", "0003_auto_20220228_1759"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charity",
            name="charity_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The type of the charity displayed on the public register of charities. Only the main parent charity will have a value for this field (i.e. linked_charity_number=0).",
                max_length=255,
                null=True,
            ),
        ),
    ]
