# Generated by Django 4.0.3 on 2022-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccew", "0004_alter_charity_charity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charityclassification",
            name="classification_type",
            field=models.CharField(
                blank=True,
                choices=[("What", "What"), ("How", "How"), ("Who", "Who")],
                help_text="The type of the classification. What - What the charity does. How - How the charity helps. Who - Who the charity helps",
                max_length=255,
                null=True,
            ),
        ),
    ]
